# Generated by Django 4.2.6 on 2023-11-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='file_type',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
