# Generated by Django 4.2.6 on 2023-11-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_metadata_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='processing_time',
        ),
    ]
