# Generated by Django 4.2.6 on 2023-11-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_metadata_processing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='chars',
        ),
    ]
